server:
  port: 8083

spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true
    remote:
      context-path: src/main/java
  servlet:
    multipart:
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MyQQ-db?useSSL=false
    username: root
    password: atri

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


---
server:
  port: 8084

spring:
  profiles: test

---
spring:
  profiles:
    active: dev
